import { test, expect } from "@playwright/test";
import { readFile, stat } from "node:fs/promises";
import path from "node:path";
test("demo login upload progress playback edit reload download and delete", async ({ page }) => {
  const errors=[];page.on("pageerror",e=>errors.push(e.message));
  await page.goto("/index.html");
  await page.getByLabel("Username").fill("demo");
  await page.getByLabel("Password").fill("wrong-password");
  await page.getByRole("button",{name:"Sign in",exact:true}).click();
  await expect(page.getByRole("alert")).toContainText("Invalid username");
  await page.getByLabel("Password").fill("demo-password");
  await page.getByRole("button",{name:"Sign in",exact:true}).click();
  await expect(page).toHaveURL(/dashboard.html/);
  await page.getByRole("link",{name:"Upload recording",exact:true}).first().click();
  const title=`E2E demo ${Date.now()}`;
  await page.getByLabel("Meeting title").fill(title);
  await page.getByLabel("Recording",{exact:true}).setInputFiles(path.resolve("../fixtures/demo.mp4"));
  const processing=page.waitForURL(/processing.html/);
  await page.getByRole("button",{name:"Upload and process"}).click();
  await processing;
  await expect(page.getByRole("heading",{name:"Processing meeting"})).toBeVisible();
  await expect(page).toHaveURL(/meeting.html\?id=/,{timeout:90000});
  await expect(page.getByRole("heading",{name:title})).toBeVisible();
  for(const name of ["Native","Roman","English"]){await page.getByRole("button",{name,exact:true}).click();await expect(page.getByRole("button",{name,exact:true})).toHaveAttribute("aria-pressed","true");}
  await expect.poll(()=>page.locator("video").evaluate(v=>v.readyState)).toBeGreaterThan(0);
  await page.locator("video").evaluate(v=>v.play());
  await expect.poll(()=>page.locator("video").evaluate(v=>v.currentTime)).toBeGreaterThan(.1);
  await page.locator(".evidence-chip").filter({hasText:"0:05"}).first().click();
  await expect.poll(()=>page.locator("video").evaluate(v=>v.currentTime)).toBeGreaterThanOrEqual(5);
  const edited="Saved browser edit survives a page reload.";
  await page.getByLabel("Edit meeting summary").fill(edited);
  await page.getByRole("button",{name:"Save summary"}).click();
  await expect(page.getByRole("status")).toHaveText("Summary saved");
  await page.reload();
  await expect(page.getByLabel("Edit meeting summary")).toHaveValue(edited);
  const downloadEvent=page.waitForEvent("download");
  await page.getByRole("button",{name:"Download transcript"}).click();
  const download=await downloadEvent;
  expect(await download.failure()).toBeNull();
  const file=await download.path();expect((await stat(file)).size).toBeGreaterThan(0);
  const rows=JSON.parse(await readFile(file,"utf8"));expect(rows.length).toBe(3);
  expect(rows.every(s=>s.segment_id&&s.text_native&&["accepted","review","rejected"].includes(s.quality))).toBe(true);
  await page.getByRole("link",{name:"Meetings",exact:true}).first().click();
  await page.getByLabel("Search meetings").fill(title);
  const row=page.locator("article.meeting-row").filter({hasText:title});
  await expect(row).toBeVisible();
  page.once("dialog",dialog=>dialog.accept());await row.getByRole("button",{name:"Delete",exact:true}).click();
  await expect(row).toHaveCount(0);
  await page.getByRole("button",{name:"Sign out"}).click();await expect(page).toHaveURL(/index.html/);
  await page.goto("/meetings.html");await expect(page).toHaveURL(/index.html/);
  expect(errors).toEqual([]);
});
